sudo: required

cache: bundler

services:
  - docker

env:
  global:
  - secure: OcJDwc8XxRmCEUdBLVf7RNGxc/ObcLCZ5+PbWiZngyJ928aL0Aiip6IGc6EFz6DFLzlcT8F9bT8q8wWw3MgkzfYLUp0D66BleA1JbEw7KtWP5W6JLExh3AO/ZRRNBUr7rLZE3MP2hAFvQIwGVF82p53Q33//pgaCsLegFmXkGfS21JcX0i012eTJHjczo/Z1+Aa9Dn4fjVmXfY94sc7biRk4eXKJsKdsJkj4pV+VlXnkYoTreOE6mRhjR4Y/l8OyTXwb9fFxf3TBmO2CY4pFIY0bJVtWVvynnn/8qR1TJPF9Vf/L9M2hL4Sn4CkZ5F1nCDDEbzG6ljvplGdw60Z87IMz6lmmkkYxooJBCJCFAfQ2O6GNYcszYuG9YuZNJtwQQ6uNh9nxMu+iuZoc4xtojX5R+W5P4kq6sIcwnIXdNy56EB6R3rjjr/7zNsrDRxRFUHV1pPtLcq9r0dttAuUVLFMFmIS1ULltpxAScI0aZgrCWcMYZaJ4djKXq4xT0IpzmC013dce95xGuMWgU5cCvOyJsrJgzd3Xvt7kkfHZQKGoMz7RmPfhbK66ZluVFz9Q0D6D66x9IS26d770W7agaUdTi8GKrVS8cy1WEBD0QhEdDyBdSwArsOlydvhs+uO7M5qi40AC7oUPuKbqZRQ5jqLIdZxWr1TWpas8a110BZM=
  - secure: abHZVhb9wCPq6T8X8Fwqa68pHgZNtELPzulKjSglaurh+UsJDL4iTjk0fhxkMrP9ox1rSUrN6gIsYbDzjVNZqbOeB2BzDensaFSqK8iyGqpye5sgti/ohbvCXAwDM/lROJHcpZnXJe52Ja1DQQ+ym1H/Ge0izmUa1pggqusqI5qFDBvByyK7toWvDLcVmIJcORk3y7XOdqw2+mHF9Z4biVfVfkDy0NYWELFCRimzmXGsmk2VCrCR9fzn4vuX9DN8SjZ0AcUrVyNuyphLpLj4+CJLlVyKzdkmXlFpCiQIhMcvv/PDRfcPrTafoz2qZ2L3sJPO9B5DB8S23r+IT0ilcJg+cIFkKK4B72aPJQlR5CZFeEiowGunf/Cgr/6iRvn9xhepujr3L/0WmkVrs+9ITUDZg3OpV21pk6j3/Of38jFqEjFQg/QcjLwGIu/sR2F8AskAyMoRl+168qt0uilhmWt5BXnjHdvnpyI8bitQabh7wohEFmyknyCo7GUn+0FsXNm+1t2Bq9hTbziDBGInBjaHPEbfv68Hu3ORQQVJgiK03Krxz0y8eeaUdZLSxlM0PuDQKfnqfAYYNoK3us2ECsp+otTGwtUEQ7oILO+ii8DcBWqgGAidzKqP3dGrGpBpSZk4ukCEE/yCRzhI0oXJlgFQ9k5k+9He5No3l4uMQJY=

  matrix:
    - LATEST=0 SYLIUS_VERSION=1.1.17 SYLIUS_SHORT_VERSION=11 PHP_VERSION=7.2 PHP_SHORT_VERSION=72
    - LATEST=0 SYLIUS_VERSION=1.1.17 SYLIUS_SHORT_VERSION=11 PHP_VERSION=7.1 PHP_SHORT_VERSION=71

    - LATEST=0 SYLIUS_VERSION=1.2.16 SYLIUS_SHORT_VERSION=12 PHP_VERSION=7.3 PHP_SHORT_VERSION=73
    - LATEST=0 SYLIUS_VERSION=1.2.16 SYLIUS_SHORT_VERSION=12 PHP_VERSION=7.2 PHP_SHORT_VERSION=72

    - LATEST=0 SYLIUS_VERSION=1.3.9 SYLIUS_SHORT_VERSION=13 PHP_VERSION=7.3 PHP_SHORT_VERSION=73
    - LATEST=0 SYLIUS_VERSION=1.3.9 SYLIUS_SHORT_VERSION=13 PHP_VERSION=7.2 PHP_SHORT_VERSION=72

    - LATEST=1 SYLIUS_VERSION=1.4.1 SYLIUS_SHORT_VERSION=14 PHP_VERSION=7.3 PHP_SHORT_VERSION=73
    - LATEST=0 SYLIUS_VERSION=1.4.1 SYLIUS_SHORT_VERSION=14 PHP_VERSION=7.2 PHP_SHORT_VERSION=72

script:
  - bash docker-build.sh
  - bash docker-test.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

# Do some informational output
after_script:
  - docker images
